### ISSUE TITLE
Computer page: Add a button to deploy installed packages to another machine

### ISSUE THREAD

**Issue by theonlytruth** [schorschii/OCO-Server#14]
Please add a button to deploy selected installed packages to another machine and also a button to add selected packages to a group. The other way around these buttons exists (package page with the list of computers it is installed on):

![grafik](https://user-images.githubusercontent.com/5502973/174797855-330fc9a1-84e5-49da-8a31-ee7c8af6cb26.png)

**Comment by schorschii** [comment]
Thanks for this suggestion. Good news: it is already possible - the same buttons exist on the computer page :)
