### ISSUE TITLE
Search for Displayname and SamAccountname

### ISSUE THREAD

**Issue by VRDD** [schorschii/OCO-Server#17]
Hi,
thanks for your development! OCO is a pleasure to work with!
One request: in AD environments it could be useful, if OCO would search not only for SAMAccountname but for Displayname as well. 
Ciao
Veit

**Comment by schorschii** [comment]
Thanks!
Full display name & username search is now implemented via https://github.com/schorschii/OCO-Server/commit/048ee6d265be46612fcf7d5626279e686d306d34 and https://github.com/schorschii/OCO-Agent/commit/3916623f80ce7509f21b4c1d0f0dc66d31eb81f3.
