### ISSUE TITLE
Subfolders

### ISSUE THREAD

**Issue by theonlytruth** [schorschii/oco-server#2]
Hi schorschii,

one point I miss from my first impression and your introduction of OCO are subfolders. I would like to have a more hierarchical structure both in the computers section and the package section. If you could introduce subfolders it would be great. Maybe they should be collapsed by default.

Thanks! Great work!

**Comment by schorschii** [comment]
Thanks for your feedback! Subfolders are now available in v0.7.0. Collapsing them on the sidebar is planned for a future release.
