### ISSUE TITLE
Two packages with mutual dependencies -> Error 500

### ISSUE THREAD

**Issue by theonlytruth** [schorschii/OCO-Server#20]
Hey schorschii,

thanks for your great tool.

I have a problem with two packages which depend on each other. I added this mutual dependencies for installing them together in every case. I could also make a complete new package with all in it, but did not want to touch old installations. So this way is better for me.

When I then try to create a job with one of this package it shows me an error 500 after a while. The job is not created then.

May you have a look at this issue?

Thanks.
TheOnlyTruth

**Comment by schorschii** [comment]
Thanks for your feedback, very well observed! :)
Mutual dependencies result in an endless loop [here](https://github.com/schorschii/OCO-Server/blob/master/lib/CoreLogic.class.php#L942). I'll fix that.
