### ISSUE TITLE
Cannot create a job in beta v0.15.0

### ISSUE THREAD

**Issue by t-oster** [schorschii/OCO-Server#22]
Hi, 
I just installed v0.15.0 (client and server fresh).
I registrated a client (windows 10vm) and created a simple package.
However if I start deployment from the client, the package is not shown and if i start deployment from the package, the client is not shown, so I am unable to create a job.

**Comment by t-oster** [comment]
nevermind. I have to double click it on the left side. I just misinterpreted the UI.

**Comment by theonlytruth** [comment]
I know what you mean. I often run in the same situation, wondering why OCO was not able to create a job. But then I see i just ticked the box but not moved it to the right column. For me it is also a little weakness of the UI.
