### ISSUE TITLE
Ldap issue error 500

### ISSUE THREAD

**Issue by lyonelf** [schorschii/OCO-Server#28]
Hello,

My Json conf is validated but when i whan to sync the 1st one, i have a error 500

Apache error.log show thoses lines:

[Thu Apr 27 16:16:47.705305 2023] [php7:error] [pid 5093] [client X.X.4.60:52094] PHP Fatal error:  Uncaught Error: Call to undefined function ldap_connect() in /srv/www/oco/lib/LdapSync.class.php:53\nSta
ck trace:\n#0 /srv/www/oco/frontend/ajax-handler/settings.php(11): LdapSync->syncSystemUsers()\n#1 {main}\n  thrown in /srv/www/oco/lib/LdapSync.class.php on line 53, referer: http://1X.X3.231.1X7/index.php
?tab=users&view=settings-system-users

**Comment by schorschii** [comment]
The `php-ldap` module is missing.

**Comment by lyonelf** [comment]
Damned, yes.

Me and Linux, we are not friends :)
