### ISSUE TITLE
Windows 11 regognized in Win 10

### ISSUE THREAD

**Issue by lyonelf** [schorschii/OCO-Server#30]
![2023-04-28_10h19_10](https://user-images.githubusercontent.com/34097487/235094678-eea2c9dd-2c76-4a7a-95d5-6380248e89cc.png)

**Comment by schorschii** [comment]
This is not an OCO issue but a Windows issue as stated in the [agent docs](https://github.com/schorschii/OCO-Agent#readme) under "Windows 11 hint".

**Comment by lyonelf** [comment]
Yes but maybe you can use a WMI filter if the version is higher than 22XXXX to convert it?

**Comment by schorschii** [comment]
Maybe. Feel free to make a pull request with an appropriate patch.

**Comment by lyonelf** [comment]
Humm, i d'ont have the patch but only the command line:

select * from Win32_OperatingSystem where ((Caption like "%11%") and (ProductType="1"))


Or for subversion:

SELECT * FROM Win32_OperatingSystem WHERE (Version LIKE “%22%”) OR (Version LIKE “%22%”)
