### ISSUE TITLE
Server without fqdn

### ISSUE THREAD

**Issue by apvlv** [schorschii/OCO-Server#37]
Hello,

thank you for this project. Is it possible to set up the server without a fqdn/internal dns server but only with an IP Address?

Thanks

**Comment by schorschii** [comment]
It is possible but tricky. You need to create a certificate which is issued for your server IP address, as described in [Server-Installation.md](https://github.com/schorschii/OCO-Server/blob/master/docs/Server-Installation.md#certificate-setup). Then, make sure to use the newest agent version installation package [v1.0.2](https://github.com/schorschii/OCO-Agent/releases/tag/v1.0.2) on your clients. Only this package contains the new urllib version 2.x which can verify certificates with IP addresses.
