### ISSUE TITLE
Feature Request ? Jobs - Uninstall only

### ISSUE THREAD

**Issue by KSJakobsen** [schorschii/OCO-Server#40]
Hi,

would it be possible to implement an uninstall only job. If for example a package has been superseeded by another product. Or an End-User installed some application that we need to uninstall ? 

Kind Regards
Kai

**Comment by schorschii** [comment]
This is already possible. You can create an empty package for this: just enter your uninstall command in the "Installation procedure" field and deploy it on the desired computers.

**Comment by schorschii** [comment]
Closed due to inactivity / no response...
