### ISSUE TITLE
Self Service LDAP binding

### ISSUE THREAD

**Issue by BornTKill** [schorschii/OCO-Server#48]
Dear,

i have configured ldap (freeipa) sync for admin and self portal but I cannot log on self portal with my ldap password. It works on admin portal.

Look like ldap uuid is not matching domain_user.
can you help me ?

**Comment by BornTKill** [comment]
Hello @schorschii 

i was wondering if you need more information.

**Comment by schorschii** [comment]
Just wanted to close your other issue first.

Do you only use Linux clients with your freeipa or do you also have Windows and/or macOS machines connected with your freeipa?

**Comment by BornTKill** [comment]
Hi,

Computers (33% osx , 33% win, 33% Ubuntu) are not integrated in the freeipa domain.
We just use freeipa for LDAP/Radius + keycloak/goauthentik for authentification.

**Comment by schorschii** [comment]
> Computers (33% osx , 33% win, 33% Ubuntu) are not integrated in the freeipa domain.

OK, this means you are using local accounts to log on these client computers and you do not login with freeipa accounts? Then, the agent is not able to determine the domain user UUID for the logins. The Self Service portal currently relies on that.

I can imagine to make a configuration option to use the username as identifier instead. This means that the local user account on the machines must match the username in freeipa. Disadvantages of this solution are:
- Usernames are only unique within a domain, so it will not work in multi-domain environments.
- Username changes cannot be recognized (will be treated like 2 separate accounts).

I'll make some more tests for that soon.

**Comment by BornTKill** [comment]
Exactly. Should be great to be able to bind ldap uid as login cred.

**Comment by schorschii** [comment]
Sorry for the delay. I added an option for using the username as identifier for the LDAP sync now (see linked commit). Feedback is greatly appreciated.

**Comment by BornTKill** [comment]
@BornTKill The ldap binding is working but authentication with ldap password fail on web portal.
Any idea ?

**Comment by BornTKill** [comment]
@schorschii Sorry for bothering you. Any idea ? Did I miss something ?

**Comment by schorschii** [comment]
Sorry for the delay, I'm on vacation. I'll come back to you next week.

**Comment by BornTKill** [comment]
Sure ! Enjoy your holidays ! @schorschii

**Comment by BornTKill** [comment]
Hello @schorschii 

FYI when a user is in system users with ldap login (ldap admin group for example), oco self portal authentication is working.
However, when a user is in the same ldap but in another group (non ldap admin group for example) , authentication fails.

I hope it helps.

**Comment by schorschii** [comment]
I don't really have an idea what's the problem here. Can you please double check your self service LDAP config and post it here? Have you set the new config option `"username-as-identifier": true`? After syncing, do the domain users have a role assigned (you can see it here: https://oco.example.com/?view=settings-domain-users&tab=users), or is the role column still empty?

**Comment by BornTKill** [comment]
Hi,

Please find my config
System Users :

```
{
    "1": {
        "address": "ldap:\/\/ipa.example.com",
        "username": "uid=ldapsearch,cn=users,cn=accounts,dc=example,dc=com",
        "password": "xxxxxx",
        "query-root": "dc=example,dc=com",
        "queries": {
            "(&(objectClass=posixAccount)(memberof=cn=admin,cn=groups,cn=accounts,dc=example,dc=com))": 1
        },
        "login-binddn-query": "(&(&(objectclass=*)(memberof=cn=admin,cn=groups,cn=accounts,dc=example,dc=com))(uid=%s))",
        "attribute-matching": {
            "uid": "uid",
            "username": "uid",
            "first_name": "givenname",
            "last_name": "sn",
            "display_name": "displayname",
            "email": "mail",
            "phone": "telephonenumber",
            "mobile": "mobile",
            "description": "description"
        },
        "lock-deleted-users": true
    }
}
```

**Comment by BornTKill** [comment]
Hi @schorschii 

I had a typo in my config ...
Sorry for bothering you.

all good for now.

**Comment by schorschii** [comment]
No problem, good to know it's not a bug :)
