### ISSUE TITLE
Error 400 - Cannot move uploaded file

### ISSUE THREAD

**Issue by kondi06** [schorschii/OCO-Server#55]
installed on turnkey webmin, where there is apache and php. when trying to create a package an error appears "Error 400 - Cannot move uploaded file"

**Comment by schorschii** [comment]
Why do you closed the issue instantly? Do you fixed it? What was the problem?

**Comment by kondi06** [comment]
yes I fixed it, it turned out that I didn't give the right permissions to the directory, and I also had to remove AllowOverride All
