### ISSUE TITLE
API call to get current server version

### ISSUE THREAD

**Issue by BornTKill** [schorschii/OCO-Server#56]
Hello @schorschii ,

I was wondering if a simple GET i can retrieve the current server version ?
I check de API documentation but did not find the information.

Thank You.

**Comment by BornTKill** [comment]
Maybe parsing home page is enough ?

--
<link rel='stylesheet' type='text/css' href='css/main.css?**v=1.1.2**'>

**Comment by schorschii** [comment]
Currently not but it's no big deal, I implement it for you.
